### ISSUE TITLE
7种渐变色转

### ISSUE THREAD

**Issue by linbx08** [saitjr/LoopProgressDemo#1]
请问七种渐变色角度改怎么设置的

**Comment by saitjr** [comment]
七种渐变色？什么意思？

**Comment by linbx08** [comment]
你好,就是我的渐变色为 蓝-->绿-->黄-->橙-->红-->紫->褐 这样渐变,请问怎么弄

**Comment by saitjr** [comment]
最简单方式...直接用图，代码写出来的渐变，可能没那么平滑

**Comment by linbx08** [comment]
恩恩,谢谢.我现在是用图的,就是我们老大到时候可能会改需求要一边拖动一边画出来就麻烦了

**Comment by saitjr** [comment]
一边拖一边画？mask layer 不就好了吗？
